spring.application.name=backend
server.port=${PORT:8081}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

firebase.storage.bucket=animal-filter.firebasestorage.app
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:src/main/resources/serviceAccountKey.json}
firebase.credentials.json-base64=${FIREBASE_CREDENTIALS_BASE64:}